spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: shop-hgx
      sms:
        host: https://feginesms.market.alicloudapi.com
        path: /codeNotice
        skin: 1
        sign: 175622
  application:
    name: shop-third-party
server:
  port: 30000
logging:
  level:
    com.hgx.shop: debug
