spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4GJrGc2qWR5y8LzQNZy5
      secret-key: O8QHCbLenlqotj29H3SwfLOp6rKlU2
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: shop-hgx
  application:
    name: shop-third-party
server:
  port: 30000
logging:
  level:
    com.hgx.shop: debug
